# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"A\n\tOrderInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x14\n\x0corder_number\x18\x03 \x01(\x05\"#\n\x0bOrderNumber\x12\x14\n\x0corder_number\x18\x01 \x01(\x05\")\n\x0cRecoveryInfo\x12\x19\n\x05infos\x18\x01 \x03(\x0b\x32\n.OrderInfo\"\x07\n\x05\x45mpty2\xc8\x01\n\x0cOrderService\x12!\n\x03\x62uy\x12\n.OrderInfo\x1a\x0c.OrderNumber\"\x00\x12#\n\x05query\x12\x0c.OrderNumber\x1a\n.OrderInfo\"\x00\x12\x18\n\x04ping\x12\x06.Empty\x1a\x06.Empty\"\x00\x12+\n\rupdateReplica\x12\n.OrderInfo\x1a\x0c.OrderNumber\"\x00\x12)\n\x08recovery\x12\x0c.OrderNumber\x1a\r.RecoveryInfo\"\x00\x62\x06proto3')



_ORDERINFO = DESCRIPTOR.message_types_by_name['OrderInfo']
_ORDERNUMBER = DESCRIPTOR.message_types_by_name['OrderNumber']
_RECOVERYINFO = DESCRIPTOR.message_types_by_name['RecoveryInfo']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
OrderInfo = _reflection.GeneratedProtocolMessageType('OrderInfo', (_message.Message,), {
  'DESCRIPTOR' : _ORDERINFO,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderInfo)
  })
_sym_db.RegisterMessage(OrderInfo)

OrderNumber = _reflection.GeneratedProtocolMessageType('OrderNumber', (_message.Message,), {
  'DESCRIPTOR' : _ORDERNUMBER,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderNumber)
  })
_sym_db.RegisterMessage(OrderNumber)

RecoveryInfo = _reflection.GeneratedProtocolMessageType('RecoveryInfo', (_message.Message,), {
  'DESCRIPTOR' : _RECOVERYINFO,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:RecoveryInfo)
  })
_sym_db.RegisterMessage(RecoveryInfo)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_ORDERSERVICE = DESCRIPTOR.services_by_name['OrderService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERINFO._serialized_start=15
  _ORDERINFO._serialized_end=80
  _ORDERNUMBER._serialized_start=82
  _ORDERNUMBER._serialized_end=117
  _RECOVERYINFO._serialized_start=119
  _RECOVERYINFO._serialized_end=160
  _EMPTY._serialized_start=162
  _EMPTY._serialized_end=169
  _ORDERSERVICE._serialized_start=172
  _ORDERSERVICE._serialized_end=372
# @@protoc_insertion_point(module_scope)
