# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\"\x1c\n\x0cQueryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\",\n\nBuyRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"0\n\rQueryResponse\x12\x10\n\x08quantity\x18\x01 \x01(\x05\x12\r\n\x05price\x18\x02 \x01(\x02\"\x1b\n\x0b\x42uyResponse\x12\x0c\n\x04\x64one\x18\x01 \x01(\x05\x32^\n\x0e\x43\x61talogService\x12(\n\x05query\x12\r.QueryRequest\x1a\x0e.QueryResponse\"\x00\x12\"\n\x03\x62uy\x12\x0b.BuyRequest\x1a\x0c.BuyResponse\"\x00\x62\x06proto3')



_QUERYREQUEST = DESCRIPTOR.message_types_by_name['QueryRequest']
_BUYREQUEST = DESCRIPTOR.message_types_by_name['BuyRequest']
_QUERYRESPONSE = DESCRIPTOR.message_types_by_name['QueryResponse']
_BUYRESPONSE = DESCRIPTOR.message_types_by_name['BuyResponse']
QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

BuyRequest = _reflection.GeneratedProtocolMessageType('BuyRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUYREQUEST,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:BuyRequest)
  })
_sym_db.RegisterMessage(BuyRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)

BuyResponse = _reflection.GeneratedProtocolMessageType('BuyResponse', (_message.Message,), {
  'DESCRIPTOR' : _BUYRESPONSE,
  '__module__' : 'catalog_pb2'
  # @@protoc_insertion_point(class_scope:BuyResponse)
  })
_sym_db.RegisterMessage(BuyResponse)

_CATALOGSERVICE = DESCRIPTOR.services_by_name['CatalogService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERYREQUEST._serialized_start=17
  _QUERYREQUEST._serialized_end=45
  _BUYREQUEST._serialized_start=47
  _BUYREQUEST._serialized_end=91
  _QUERYRESPONSE._serialized_start=93
  _QUERYRESPONSE._serialized_end=141
  _BUYRESPONSE._serialized_start=143
  _BUYRESPONSE._serialized_end=170
  _CATALOGSERVICE._serialized_start=172
  _CATALOGSERVICE._serialized_end=266
# @@protoc_insertion_point(module_scope)
